# Bamboo theme {{{
# Default colors
[colors.primary]
background = '0x252623'
foreground = '0xf1e9d2'

# Normal colors
[colors.normal]
black = '0x1c1e1b'
red = '0xe75a7c'
green = '0x8fb573'
yellow = '0xdbb651'
blue = '0x57a5e5'
magenta = '0xaaaaff'
cyan = '0x70c2be'
white = '0xf1e9d2'

# Bright colors
[colors.bright]
black = '0x5b5e5a'
red = '0xe75a7c'
green = '0x8fb573'
yellow = '0xdbb651'
blue = '0x57a5e5'
magenta = '0xaaaaff'
cyan = '0x70c2be'
white = '0xfff8f0'
# }}}

[font]
size = 13.0
offset = { x = 1, y = 1 }

[font.bold]
family = "GeistMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "GeistMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "GeistMono Nerd Font"
style = "Italic"

[font.normal]
family = "GeistMono Nerd Font"
style = "Regular"

[window]
blur = true
opacity = 0.7
padding = { x = 10, y = 5 }
